import type { Order, Customer, Product, RevenueData } from "@/types";

// ─── Orders ─────────────────────────────────────────────────────────
export const MOCK_ORDERS: Order[] = [
  {
    id: "1",
    orderNumber: "NTD-2024-08471",
    customer: "Priya Sharma",
    company: "Infosys Ltd.",
    occasion: "Diwali",
    items: 3,
    quantity: 120,
    total: 53880,
    status: "processing",
    deliveryDate: "2024-10-28",
    createdAt: "2024-10-15",
    address: "Bengaluru, Karnataka",
  },
  {
    id: "2",
    orderNumber: "NTD-2024-08392",
    customer: "Rahul Mehta",
    company: "TCS Pvt Ltd.",
    occasion: "Corporate",
    items: 2,
    quantity: 250,
    total: 99750,
    status: "shipped",
    deliveryDate: "2024-10-20",
    createdAt: "2024-10-10",
    address: "Mumbai, Maharashtra",
  },
  {
    id: "3",
    orderNumber: "NTD-2024-08301",
    customer: "Anjali Patel",
    company: "Wipro Technologies",
    occasion: "New Year",
    items: 5,
    quantity: 500,
    total: 174500,
    status: "delivered",
    deliveryDate: "2024-10-05",
    createdAt: "2024-09-28",
    address: "Pune, Maharashtra",
  },
  {
    id: "4",
    orderNumber: "NTD-2024-08187",
    customer: "Vikram Singh",
    company: "HCL Technologies",
    occasion: "Diwali",
    items: 4,
    quantity: 80,
    total: 35920,
    status: "pending",
    deliveryDate: "2024-10-30",
    createdAt: "2024-10-18",
    address: "Noida, Uttar Pradesh",
  },
  {
    id: "5",
    orderNumber: "NTD-2024-08052",
    customer: "Meera Krishnan",
    company: "Zomato Ltd.",
    occasion: "Eid",
    items: 2,
    quantity: 60,
    total: 26940,
    status: "delivered",
    deliveryDate: "2024-09-15",
    createdAt: "2024-09-05",
    address: "Hyderabad, Telangana",
  },
  {
    id: "6",
    orderNumber: "NTD-2024-07981",
    customer: "Arjun Kapoor",
    company: "Flipkart",
    occasion: "Corporate",
    items: 3,
    quantity: 200,
    total: 89800,
    status: "cancelled",
    deliveryDate: "2024-09-20",
    createdAt: "2024-09-10",
    address: "Bengaluru, Karnataka",
  },
  {
    id: "7",
    orderNumber: "NTD-2024-07854",
    customer: "Nisha Gupta",
    company: "Amazon India",
    occasion: "Holi",
    items: 2,
    quantity: 100,
    total: 44900,
    status: "delivered",
    deliveryDate: "2024-03-25",
    createdAt: "2024-03-10",
    address: "Delhi, NCR",
  },
  {
    id: "8",
    orderNumber: "NTD-2024-07720",
    customer: "Suresh Babu",
    company: "Tech Mahindra",
    occasion: "Christmas",
    items: 4,
    quantity: 150,
    total: 67350,
    status: "shipped",
    deliveryDate: "2024-12-22",
    createdAt: "2024-12-10",
    address: "Chennai, Tamil Nadu",
  },
];

// ─── Customers ──────────────────────────────────────────────────────
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Priya Sharma",
    company: "Infosys Ltd.",
    email: "priya.sharma@infosys.com",
    phone: "+91 98765 43210",
    totalOrders: 4,
    totalSpend: 185000,
    lastOrder: "2024-10-15",
    status: "active",
    avatar: "PS",
  },
  {
    id: "c2",
    name: "Rahul Mehta",
    company: "TCS Pvt Ltd.",
    email: "rahul.mehta@tcs.com",
    phone: "+91 87654 32109",
    totalOrders: 7,
    totalSpend: 342000,
    lastOrder: "2024-10-10",
    status: "active",
    avatar: "RM",
  },
  {
    id: "c3",
    name: "Anjali Patel",
    company: "Wipro Technologies",
    email: "anjali.patel@wipro.com",
    phone: "+91 76543 21098",
    totalOrders: 3,
    totalSpend: 220000,
    lastOrder: "2024-09-28",
    status: "active",
    avatar: "AP",
  },
  {
    id: "c4",
    name: "Vikram Singh",
    company: "HCL Technologies",
    email: "vikram.singh@hcl.com",
    phone: "+91 65432 10987",
    totalOrders: 2,
    totalSpend: 78000,
    lastOrder: "2024-10-18",
    status: "active",
    avatar: "VS",
  },
  {
    id: "c5",
    name: "Meera Krishnan",
    company: "Zomato Ltd.",
    email: "meera.k@zomato.com",
    phone: "+91 54321 09876",
    totalOrders: 5,
    totalSpend: 156000,
    lastOrder: "2024-09-05",
    status: "inactive",
    avatar: "MK",
  },
  {
    id: "c6",
    name: "Arjun Kapoor",
    company: "Flipkart",
    email: "arjun.k@flipkart.com",
    phone: "+91 43210 98765",
    totalOrders: 1,
    totalSpend: 89800,
    lastOrder: "2024-09-10",
    status: "inactive",
    avatar: "AK",
  },
];

// ─── Products ───────────────────────────────────────────────────────
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Kaju Katli Gift Box",
    brand: "Haldirams",
    category: "sweets",
    price: 299,
    originalPrice: 399,
    weight: "500g",
    shelfLife: "30 days",
    minOrder: 10,
    rating: 4.8,
    reviews: 1240,
    emoji: "🍬",
    badge: "Best Seller",
    inStock: true,
    tags: ["festive", "diwali", "sweet"],
  },
  {
    id: 2,
    name: "Premium Cashew Pack",
    brand: "Nutraj",
    category: "nuts",
    price: 249,
    originalPrice: 329,
    weight: "250g",
    shelfLife: "6 months",
    minOrder: 10,
    rating: 4.6,
    reviews: 876,
    emoji: "🥜",
    badge: "",
    inStock: true,
    tags: ["healthy", "corporate"],
  },
  {
    id: 3,
    name: "Assorted Dry Fruits",
    brand: "Nutado Select",
    category: "dry-fruits",
    price: 399,
    originalPrice: 499,
    weight: "400g",
    shelfLife: "6 months",
    minOrder: 5,
    rating: 4.9,
    reviews: 2100,
    emoji: "🎁",
    badge: "Top Rated",
    inStock: true,
    tags: ["premium", "gifting"],
  },
  {
    id: 4,
    name: "Dark Chocolate Box",
    brand: "Cadbury",
    category: "chocolates",
    price: 349,
    originalPrice: 449,
    weight: "300g",
    shelfLife: "12 months",
    minOrder: 10,
    rating: 4.7,
    reviews: 654,
    emoji: "🍫",
    badge: "",
    inStock: true,
    tags: ["chocolate", "gifting"],
  },
  {
    id: 5,
    name: "Mixed Namkeen Pack",
    brand: "Bikano",
    category: "chips",
    price: 199,
    originalPrice: 249,
    weight: "500g",
    shelfLife: "4 months",
    minOrder: 20,
    rating: 4.5,
    reviews: 432,
    emoji: "🥨",
    badge: "Popular",
    inStock: true,
    tags: ["snack", "everyday"],
  },
  {
    id: 6,
    name: "Dates & Figs Box",
    brand: "Nutado Select",
    category: "dry-fruits",
    price: 449,
    originalPrice: 599,
    weight: "500g",
    shelfLife: "6 months",
    minOrder: 5,
    rating: 4.8,
    reviews: 789,
    emoji: "🌿",
    badge: "",
    inStock: false,
    tags: ["premium", "healthy"],
  },
  {
    id: 7,
    name: "Almond Raisin Mix",
    brand: "Happilo",
    category: "nuts",
    price: 329,
    originalPrice: 429,
    weight: "300g",
    shelfLife: "6 months",
    minOrder: 10,
    rating: 4.6,
    reviews: 521,
    emoji: "✨",
    badge: "",
    inStock: true,
    tags: ["healthy", "nuts"],
  },
  {
    id: 8,
    name: "Gourmet Cookie Box",
    brand: "Unibic",
    category: "cookies",
    price: 279,
    originalPrice: 349,
    weight: "400g",
    shelfLife: "3 months",
    minOrder: 12,
    rating: 4.4,
    reviews: 365,
    emoji: "🍪",
    badge: "",
    inStock: true,
    tags: ["sweet", "gifting"],
  },
];

// ─── Revenue data ────────────────────────────────────────────────────
export const MOCK_REVENUE: RevenueData[] = [
  { month: "Jan", revenue: 185000, orders: 42 },
  { month: "Feb", revenue: 210000, orders: 51 },
  { month: "Mar", revenue: 275000, orders: 68 },
  { month: "Apr", revenue: 190000, orders: 44 },
  { month: "May", revenue: 230000, orders: 59 },
  { month: "Jun", revenue: 195000, orders: 47 },
  { month: "Jul", revenue: 310000, orders: 76 },
  { month: "Aug", revenue: 285000, orders: 69 },
  { month: "Sep", revenue: 340000, orders: 84 },
  { month: "Oct", revenue: 520000, orders: 128 },
  { month: "Nov", revenue: 460000, orders: 112 },
  { month: "Dec", revenue: 390000, orders: 95 },
];
